In [2]:
import numpy as np

# 1) Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

# Vektor tek boyutlu, matris ki boyutludur.

In [8]:
# 2) 10 elemanli bir listeden NumPy Array’i olusturunuz.


a=[i for i in range(10)]

np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 3) Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.


np.zeros((10,10),dtype=int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
# 4) Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

np.ones((10,10), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
# 5) Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

np.full((10,10), 9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [10]:
# 6) 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [11]:
# 7) -1 ile 1 arasinda 30 adet Array olusturunuz.

np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [12]:
# 8) 0 ile 30 arasinda 5x6’lik bir matris olusturun.

np.random.randint(0,30,(5,6))

array([[ 1,  0, 17, 29,  5, 18],
       [13, 15,  1,  9,  8,  2],
       [ 0,  2,  1, 11, 12,  1],
       [29, 21, 13, 27, 28, 21],
       [ 0, 27, 11,  4, 15,  9]])

In [19]:
# 9) Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

arr=np.random.randint(2,30, (10,10))

for i in range(10):
    for j in range(10):
        if i==j or i+j==9:
            arr[i,j]=1

arr

array([[ 1, 16,  4, 22, 14,  8,  2, 15, 10,  1],
       [10,  1, 17, 29,  7, 10,  4, 16,  1, 29],
       [18, 17,  1, 10, 24, 18, 12,  1, 10,  8],
       [25, 15,  2,  1,  6, 14,  1,  3,  5, 24],
       [ 8, 24,  3,  4,  1,  1, 11, 16, 26,  7],
       [ 3, 10, 24, 27,  1,  1, 15, 16, 24, 15],
       [17, 16, 23,  1, 10, 27,  1, 19,  9, 25],
       [ 5, 21,  1, 18, 14, 22,  4,  1, 18, 11],
       [18,  1, 18, 19, 13, 15, 10, 16,  1, 18],
       [ 1, 24,  9,  8, 26,  7,  5, 25, 27,  1]])

In [23]:
# 10) 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;

# eleman sayisini
# boyut bilgisini/sayisini
# satir X sutun bilgisini
# veri tipini numpy metodlariyla yazdiriniz.


arr=np.random.randint(0,10,size=(5,10))

print("eleman sayısı: ", arr.size, "\nboyut: ", arr.ndim, "\nsatırXsutun: ", arr.shape, "\nveri tipi: ", arr.dtype)

eleman sayısı:  50 
boyut:  2 
satırXsutun:  (5, 10) 
veri tipi:  int32


In [25]:
# 11) 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

np.random.randint(0,10, size=(3,4,7))

array([[[6, 8, 3, 6, 0, 1, 0],
        [5, 4, 7, 5, 8, 3, 0],
        [5, 7, 9, 7, 8, 3, 6],
        [4, 0, 7, 3, 8, 6, 9]],

       [[4, 5, 8, 1, 3, 4, 4],
        [5, 3, 8, 3, 3, 8, 4],
        [5, 5, 7, 5, 9, 3, 2],
        [7, 7, 9, 5, 8, 0, 3]],

       [[7, 0, 8, 8, 1, 4, 2],
        [9, 6, 5, 9, 2, 9, 7],
        [3, 9, 3, 5, 3, 4, 3],
        [2, 5, 9, 4, 3, 6, 3]]])

In [36]:
# 12) Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

a= np.random.randint(10,size=6)
b=a.reshape(3,2)

print("first: \n", a,"\n\nsecond: \n", b)

first: 
 [6 9 6 9 7 6] 

second: 
 [[6 9]
 [6 9]
 [7 6]]


In [37]:
# 13) 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
c=np.array([3,4,5,6])
d=np.array([4,5,6,7])

np.concatenate([a,b,c,d])

array([1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7])

In [72]:
# 14) 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz

a=np.random.randint(0,10,size=(2,2))
b=np.random.randint(0,10,size=(2,1))

print("first: \n",a,"\n\nsecond: \n",b)

np.concatenate([a,b],axis=1)

first: 
 [[8 3]
 [7 9]] 

second: 
 [[5]
 [4]]


array([[8, 3, 5],
       [7, 9, 4]])

In [ ]:
# 15) Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

# axis=0 altına ilave satır olarak ekler, axis=1 yanına ilave sütun olarak ekler

In [73]:
# 16) Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

a=np.random.randint(0,10,size=(3,5))
b=np.random.randint(0,10,size=(3,1))
c=np.random.randint(0,10,size=(1,6))

print("first: \n",a,"\n\nsecond: \n",b, "\n\nthird: \n",c )

x= np.concatenate([a,b],axis=1)
np.concatenate([x,c])

first: 
 [[4 5 4 8 3]
 [5 1 6 0 7]
 [1 4 2 6 0]] 

second: 
 [[9]
 [5]
 [3]] 

third: 
 [[0 1 6 5 7 1]]


array([[4, 5, 4, 8, 3, 9],
       [5, 1, 6, 0, 7, 5],
       [1, 4, 2, 6, 0, 3],
       [0, 1, 6, 5, 7, 1]])

In [75]:
# 17) 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

lst=[i for i in range(10)]

np.split(lst,[2,4,6,8])

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [96]:
# 18) Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

arr=np.random.randint(2,10,size=5)
print("original array",arr)

sorted_arr=np.sort(arr)

print("sorted array",sorted_arr)

for i in range(arr.size):
    print("Index of ",arr[i],"is " , list(sorted_arr).index(arr[i]))

original array [7 2 5 7 6]
sorted array [2 5 6 7 7]
Index of  7 is  3
Index of  2 is  0
Index of  5 is  1
Index of  7 is  3
Index of  6 is  2


In [99]:
# 19) 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

indx=[3,5,7]

first=np.random.randint(50,size=20)

print(first)

print(first[indx])


[49  9 26  1 12 26 44 47 31  9 37 37 31 10 22 32 28 15 43  4]
[ 1 26 47]


In [101]:
# 20) 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

arr=np.random.randint(50,size=10)
print(arr)

arr[4]=999

print(arr)


[47 42 15 21 12 12 38 18 21  9]
[ 47  42  15  21 999  12  38  18  21   9]


In [ ]:
# 21) “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip 
# bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

# Diagonal Matrix: Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan 
# tüm elemanlar sıfır ise bu matrise köşegen (diagonal) matris denir.

# Trace of Matrix: Köşegen üzerindeki elemanların toplamıdır

In [110]:
# 22) 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

arr= np.eye(5,dtype=int)

for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i,j]==1:
            arr[i,j]=np.random.randint(2,20)

print(arr)

for i in range(len(arr)):
    for j in range(len(arr)):
        if i==j:
            print("value of index of ", i, j, " is ", arr[i,j])

[[18  0  0  0  0]
 [ 0  8  0  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0 19]]
value of index of  0 0  is  18
value of index of  1 1  is  8
value of index of  2 2  is  2
value of index of  3 3  is  3
value of index of  4 4  is  19


In [112]:
# 23) 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.


arr= np.arange(10,20)
print(arr)
print()
print(arr[3:])

[10 11 12 13 14 15 16 17 18 19]

[13 14 15 16 17 18 19]


In [124]:
# 24) 10X10 luk bir matris olusturunuz ve ;
# 3.satir ve 5.sutuna ulasiniz.
# 5.sutunun tum satirlarina ulasiniz.
# Tum sutunlarin 2.satirlarina ulasiniz.
# tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
# satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
# satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
# sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
# 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

arr= np.random.randint(50, size=(10,10))
print(arr)
print()
print(arr[3,5])
print()
print(arr[:,5])
print()
print(arr[2,:])
print()
print(arr[2:7,:])
print()
print(arr[2:5,3:7])
print()
print(arr[5:,:4])
print()
print(arr[:,0:-1:3])
print()
print(arr[5:,:4])
print()
arr[5,5]=1986
print(arr)

[[ 4  4 18  2 16 41 39 34 40 11]
 [13 37 49 19 27 35  0 24 28 14]
 [16  9 36 23 25 35 32 21  2 27]
 [35 43 25 29 11 23 31 20 42 22]
 [15 32 14  8 33  0 16 14  0  5]
 [ 8  7 45  9  9  9 30  2 33 43]
 [46  3 22 49 45 34  0 47 43 36]
 [20  8  7 37 29 14  0 15  0 20]
 [13 36 16 13 34 22  9  3 36 35]
 [29  7  3 40 16 16  6  0 22  2]]

23

[41 35 35 23  0  9 34 14 22 16]

[16  9 36 23 25 35 32 21  2 27]

[[16  9 36 23 25 35 32 21  2 27]
 [35 43 25 29 11 23 31 20 42 22]
 [15 32 14  8 33  0 16 14  0  5]
 [ 8  7 45  9  9  9 30  2 33 43]
 [46  3 22 49 45 34  0 47 43 36]]

[[23 25 35 32]
 [29 11 23 31]
 [ 8 33  0 16]]

[[ 8  7 45  9]
 [46  3 22 49]
 [20  8  7 37]
 [13 36 16 13]
 [29  7  3 40]]

[[ 4  2 39]
 [13 19  0]
 [16 23 32]
 [35 29 31]
 [15  8 16]
 [ 8  9 30]
 [46 49  0]
 [20 37  0]
 [13 13  9]
 [29 40  6]]

[[ 8  7 45  9]
 [46  3 22 49]
 [20  8  7 37]
 [13 36 16 13]
 [29  7  3 40]]

[[   4    4   18    2   16   41   39   34   40   11]
 [  13   37   49   19   27   35    0   24   28   14]
 [

In [134]:
# 25) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
# 
# 20 den buyuk olan kac deger var.
# 30’dan kucuk kac deger var
# icerisinde 33 gecen kac deger var
# olusturulan arrayin tum elemanlarini 5 ile carpin.
# olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

arr=np.arange(0,50,5)
print(arr)
print()
print("20 den büyük kaç sayı: ", len(list(arr[arr>20]))  )
print()
print("30 dan küçük kaç sayı: ", len(list(arr[arr<30]))  )
print()
print("icerisinde 33 gecen kaç sayı: ", len(list(arr[arr>=33]))  )
print()
print(arr*5)
print()
print(arr%2)

[ 0  5 10 15 20 25 30 35 40 45]

20 den büyük kaç sayı:  5

30 dan küçük kaç sayı:  6

icerisinde 33 gecen kaç sayı:  3

[  0  25  50  75 100 125 150 175 200 225]

[0 1 0 1 0 1 0 1 0 1]


In [148]:
# 26) 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
# orlamasini aliniz.
# standart sapmasini aliniz.
# varyansini aliniz.
# median’ini aliniz.
# en kucuk degeri bulunuz.
# en buyuk degeri bulunuz.

arr=np.random.rand(50)
print("array: ",arr)
print()
print("mean: ",arr.mean())
print("std: ",arr.std())
print("var: ",arr.var())
print("median: ",np.median(arr))
print("min: ",arr.min())
print("max: ",arr.max())




array:  [0.70552719 0.22772693 0.63441996 0.31360012 0.63314249 0.76180622
 0.23354268 0.79594783 0.39639694 0.56949152 0.13075236 0.345238
 0.34932602 0.15516316 0.43564737 0.32737012 0.29558776 0.12188934
 0.62653679 0.81274903 0.45208012 0.46957896 0.98802055 0.55067113
 0.95601697 0.24207469 0.25640963 0.73072759 0.69207734 0.41730506
 0.22258333 0.37955168 0.74509796 0.6952634  0.025012   0.56237016
 0.40152799 0.4392819  0.91952729 0.12667258 0.16912988 0.28598546
 0.00857965 0.3106346  0.96840125 0.06368623 0.08212393 0.72321536
 0.34049118 0.82744367]

mean:  0.4584680680334527
std:  0.2683267190243026
var:  0.07199922814234705
median:  0.40941652561062564
min:  0.00857964699094027
max:  0.9880205547646872


In [ ]:
# 27) Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.

# numpy'ın tek boyutlu arraylerine vektör denir, pandas da ise series denir 
# numpy'ın iki boyutlu arraylerine matris denir, pandas da ise data frame dir.
# pandas'ta seriyi yazdırdığımızda direk index numarası ile birlikte gelir



In [149]:
# 28) Indexi buyuk harflerden olusan, icinde farkli veri tipleri bulunan 5 elemanli bir seri olusturunuz.

import pandas as pd

pd.Series([1,2,3,4,5], index=("A","B","C","D","E"))

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [150]:
# 29) Key’ler ulke adlari, value’lar baskentleri olacak sekilde 5 elemanli bir sozluk olusturup 
# onu seriye ceviriniz. (ornek: fransa:paris)


dict={"Fransa":"Paris", "Almanya":"Berlin","Ispanya":"Madrid" }

pd.Series(dict)

Fransa      Paris
Almanya    Berlin
Ispanya    Madrid
dtype: object

In [183]:
# 30) 10 elemanli random bir vektor olusturun.

# Vektoru seriye cevirip indexleri str olarak belirleyin. (ornek: a,b,c,d,e,f,g.. seklinde)
# Index ismine gore serinin 3. elemanina ulasin. (ornek: c indexine karsilik gelen deger)
# Serinin index sirasina gore 1. Elamanina ulasin.
# Index ismine gore serinin 2. Ve 7. Elemanlarina ayni anda ulasin. (Ornek: b ve g indexine karsilik gelen degerler)
# Index ismi ile serinin 2. Ve 7. Elemanlari arasindaki degerleri yazdirin. (Ornek: b,c,d,e,f,g indexlerine karsilik gelen degerler)
# Index sirasiyla serinin 4. indexinden son indexine kadar olan degerleri yazdirin.

vec=np.random.randint(30,size=10)
print(vec)
print()
seri=pd.Series(vec,index=("a","b","c","d","e","f","g","h","l","m"))
print(seri)
print()
print("c indexi için değer: ", seri["c"])
print()
print(seri.head(1)) #serinin birinci elemanı
print()
print(seri[[0]]) #serinin birinci elemanı
print()
print(seri[["b","g"]]) #serinin ikinci ve yedinci elemanı
print()
print(seri[[1,6]]) #serinin ikinci ve yedinci elemanı
print()
print(seri["c":"h"]) #serinin ikinci ve yedinci elemanı arası
print()
print(seri[2:7])
print()
print(seri[4:])


[ 3  1  5 19 23 25  8 15  2  8]

a     3
b     1
c     5
d    19
e    23
f    25
g     8
h    15
l     2
m     8
dtype: int32

c indexi için değer:  5

a    3
dtype: int32

a    3
dtype: int32

b    1
g    8
dtype: int32

b    1
g    8
dtype: int32

c     5
d    19
e    23
f    25
g     8
h    15
dtype: int32

c     5
d    19
e    23
f    25
g     8
dtype: int32

e    23
f    25
g     8
h    15
l     2
m     8
dtype: int32


In [208]:
# 31) 2 adet 5 elemanli seri olusturun.

# Olusturdugunuz serileri birlestirin.
# Birlesen 10 elemanli serinin indexini 1’den 10’a kadar olacak sekilde duzenleyin.
# Indexini duzenlediginiz seride, loc ve iloc metodlari ile, indexi 4,5,6 olan degerlere ulasin.

seri_1=pd.Series([1,2,3,4,5])
seri_2=pd.Series([2,3,4,5,6])

con_seri=pd.concat([seri_1,seri_2])

con_seri.index=[1,2,3,4,5,6,7,8,9,10]

con_seri.loc[[4,5,6]]
con_seri.iloc[[3,4,5]]


5    5
6    2
7    3
dtype: int64

In [278]:
i=0
while True:
    i+=1
    m1=np.random.rand(16).reshape(4,4)
    m2=np.random.rand(16).reshape(4,4)
    m3=m1-m2

    v1=np.diag(m3)
    if v1.min()>-0.1 and v1.max()<0.1:
        break
    
print(f"{i}'ninci denemede sonuç bulunmuştur")
print()
print(v1)



647'ninci denemede sonuç bulunmuştur

[ 0.05782702 -0.06009845  0.04849229  0.04315903]


In [279]:
i=0
while True:
    i+=1
    m1=np.random.rand(400).reshape(20,20)
    m2=np.random.rand(400).reshape(20,20)
    m3=m1-m2

    v1=np.diag(m3)
    if v1.min()>-0.1 and v1.max()<0.1:
        break
    
print(f"{i}'ninci denemede sonuç bulunmuştur")
print()
print(v1)

KeyboardInterrupt: 